import LegalPage from "./LegalPage";

export default function Privacy() {
  return <LegalPage kind="privacy">
    <section aria-labelledby="privacy-about"><h2 id="privacy-about">About Axon</h2><p>Axon is a study companion for Cambridge students. It lets a guardian create a student profile, scan marked exam papers, review what was read from them, and understand learning patterns. This policy describes the data used to provide those features; it does not claim a certification or legal status that has not been independently confirmed.</p></section>
    <section aria-labelledby="privacy-collect"><h2 id="privacy-collect">What we collect</h2>
      <h3>Account and authentication data</h3><p>We process a guardian&rsquo;s email address or phone number, authentication provider details, account identifiers, and session/security records needed to sign in and protect the account. A student profile can include a first name, stage, subjects and an avatar choice.</p>
      <h3>Study content and scans</h3><p>We process study records, paper metadata, review decisions, marks entered or confirmed by a person, and uploaded or camera-captured exam pages. Processing can create page crops, transcriptions, question regions, quality findings and explanations. Axon&rsquo;s model is not permitted to award marks.</p>
      <h3>Device, storage and operational data</h3><p>The app may receive browser/device type, network and request information, timestamps, and error or security logs. It uses local storage for necessary display preferences, offline app data, drafts and authentication session continuity. Axon currently does not use advertising cookies or install a separate marketing analytics tracker.</p>
    </section>
    <section aria-labelledby="privacy-why"><h2 id="privacy-why">Why and how data is used</h2><p>Data is used to authenticate guardians, provide and secure the product, upload and analyse papers, preserve review provenance, remember necessary preferences, support billing where selected, diagnose failures, prevent abuse, and meet legitimate record-keeping needs. Study content is treated as material to analyse, never as instructions to the processing system.</p></section>
    <section aria-labelledby="privacy-services"><h2 id="privacy-services">Services involved</h2><p>Axon uses Supabase for authentication and application data, Cloudflare infrastructure and object storage for delivery and paper files, model providers routed through OpenRouter for extraction and explanations, and Stripe when paid billing is used. Authentication may also involve Google or Apple when selected. These providers process only the data needed for their role, subject to Axon&rsquo;s configuration and their own terms. [OWNER TO CONFIRM: complete processor list and links to current provider privacy notices]</p></section>
    <section aria-labelledby="privacy-retention"><h2 id="privacy-retention">Retention and deletion</h2><p>Account and study data is kept while it is needed to provide the account and for necessary operational or legal records. Exact production retention periods have not been supplied. [OWNER TO CONFIRM: retention schedule for uploads, backups, logs and billing records]</p><p>A guardian can request account deletion from Settings. Uploaded storage objects are removed before the authentication account is released. Some de-identified guardian and student tombstone records and the append-only consent ledger remain because they preserve the history of consent; personal fields are stripped rather than kept in those records.</p></section>
    <section aria-labelledby="privacy-choices"><h2 id="privacy-choices">Your choices</h2><p>Guardians can review or withdraw optional study-processing choices in the product, change display preferences, download available data, or request account removal. Necessary storage cannot be disabled inside Axon because it supports sign-in, security, drafts and requested app behavior. If optional analytics is introduced later, it must remain off until an appropriate choice is recorded and this policy will be updated.</p></section>
    <section aria-labelledby="privacy-security"><h2 id="privacy-security">Security</h2><p>Axon uses authenticated requests, row-level access controls, short-lived upload capabilities, encrypted HTTPS transport on production origins, and review provenance intended to reduce cross-account access and fabricated scan results. No internet service can promise absolute security.</p></section>
    <section aria-labelledby="privacy-minors"><h2 id="privacy-minors">Children and guardians</h2><p>Axon is designed for students, including minors, but the guardian owns the authenticated account and makes the consent decisions used for a student profile. A student should not create or manage the guardian account independently. [OWNER TO CONFIRM: supported countries, minimum ages and guardian-verification/legal wording]</p></section>
    <section aria-labelledby="privacy-international"><h2 id="privacy-international">International handling</h2><p>Infrastructure and providers may process data in more than one country. Axon does not make a data-residency guarantee here. [OWNER TO CONFIRM: applicable transfer mechanism and intended launch territories]</p></section>
    <section aria-labelledby="privacy-updates"><h2 id="privacy-updates">Updates and contact</h2><p>Material changes will be dated here and, when they change consent purposes, the product is designed to request a new decision rather than silently reuse an old one. Questions, privacy requests and complaints can be sent to [OWNER TO CONFIRM: support/privacy contact email and postal contact].</p></section>
  </LegalPage>;
}
