import LegalPage from "./LegalPage";

export default function Terms() {
  return <LegalPage kind="terms">
    <section><h2>1. Acceptance</h2><p>By creating an account or using Axon, you agree to these terms. If you manage an account for a student, you confirm that you are authorised to make the relevant account and consent decisions. If you do not agree, do not use the service.</p></section>
    <section><h2>2. Eligibility and account responsibility</h2><p>The guardian account holder is responsible for accurate information, safeguarding sign-in methods, activity under the account, and supervising a minor&rsquo;s use. [OWNER TO CONFIRM: contracting entity, launch territories and minimum account-holder age]</p></section>
    <section><h2>3. Acceptable use</h2><p>Use Axon for lawful study and learning purposes. Do not probe or bypass security, access another person&rsquo;s data, automate abusive traffic, disrupt the service, misuse scanner or model capacity, introduce malware, or upload unlawful, harmful or exploitative material.</p></section>
    <section><h2>4. Your content</h2><p>You keep ownership of content you upload. You must have the right to use and upload it. You give Axon only the permission needed to host, copy, crop, transcribe, analyse and display that content to operate and improve the requested product features. This permission ends when content is deleted, subject to technical backups and records that must legitimately remain. Do not upload material you are not authorised to use.</p></section>
    <section><h2>5. Axon intellectual property</h2><p>Axon&rsquo;s software, branding and original product materials belong to their respective owners. These terms grant a limited, personal, revocable right to use the service, not ownership of the product or a right to copy or resell it.</p></section>
    <section><h2>6. Availability and changes</h2><p>Axon may change, suspend or discontinue features, and the service may occasionally be unavailable. Scan extraction and explanations can be incomplete or mistaken; review source crops and use teacher or school guidance for academic decisions. Axon is a study aid, not an official awarding body.</p></section>
    <section><h2>7. Suspension and termination</h2><p>Access may be limited or terminated to protect users or the service, address abuse, comply with law, or respond to a material breach. A guardian can request deletion through Settings, subject to the limited records described in the Privacy Policy.</p></section>
    <section><h2>8. Third-party services</h2><p>Authentication, hosting, storage, model processing and optional billing rely on third-party services. Their availability and separate terms may affect those features. Axon does not grant rights under a third party&rsquo;s content or service.</p></section>
    <section><h2>9. Disclaimers and liability</h2><p>The service is provided on an &ldquo;as available&rdquo; basis to the extent permitted by applicable law. [OWNER/LEGAL TO CONFIRM: warranty disclaimer and a fair limitation of liability appropriate to the contracting entity, consumer law and minor users]</p></section>
    <section><h2>10. Governing law and disputes</h2><p>[OWNER/LEGAL TO CONFIRM: governing law, venue, consumer rights, dispute process and whether arbitration applies]</p></section>
    <section><h2>11. Changes and contact</h2><p>Revised terms will show a new date here. Material changes should be communicated before they take effect where appropriate. Questions can be sent to [OWNER TO CONFIRM: legal/support email and postal contact].</p></section>
  </LegalPage>;
}
